package application;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ToccoTedd
 */
public class register_room extends javax.swing.JFrame {

    /**
     * Creates new form register_techareti
     */
 Connection conn=null;
 ResultSet rs=null;
 PreparedStatement pst=null;
    public register_room() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        conn=javaconnect.ConnecrDb();
      
      //for JOptionpane Ge'ez
       javax.swing.UIManager.put("OptionPane.font", new FontUIResource(new Font("Nyala", Font.PLAIN, 20)));
       javax.swing.UIManager.put("OptionPane.messageFont", new Font("Nyala", Font.PLAIN, 20));
       javax.swing.UIManager.put("OptionPane.buttonFont", new Font("Nyala", Font.PLAIN, 20));
      // -> end
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        last = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 700));

//        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\T#(Tedd-busi)\\HouseLottery_Module_1\\src\\images\\footerFL_notAccepted.jpg")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("src/images/condominuemmk.jpg")); // NOI18N

        jButton1.setBackground(new java.awt.Color(243, 248, 243));
        jButton1.setFont(new java.awt.Font("Nyala", 0, 24)); // NOI18N
        jButton1.setText("ይምረፁ");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nyala", 0, 24)); // NOI18N
        jLabel5.setText("ዕፃ ዓይነት ይምረፁ");

        last.setBackground(new java.awt.Color(248, 248, 248));
        last.setFont(new java.awt.Font("Nyala", 0, 24)); // NOI18N
        last.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ሓዱሽ ዕፃ", "ካብ ዝፀንሐ" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(last, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String news=last.getSelectedItem().toString();
        if(news.equalsIgnoreCase("ሓዱሽ ዕፃ")){
            int flag=JOptionPane.showConfirmDialog(null,"ናይ ቅድሚ ሐዚ ዕፃ ወዲኦም ድዮም ?");
        if(flag==0){
        int flag1=JOptionPane.showConfirmDialog(null,"ናይ ቅድሚ ሐዚ ዕፃ ዝርዝር ሓበሬታ ሒዞም ድዮም ?");
           if(flag1==0){
               String sql="TRUNCATE TABLE assigned";
            try {
                pst=conn.prepareStatement(sql);
                 pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(register_room.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sql1="TRUNCATE TABLE cond";
            try {
                pst=conn.prepareStatement(sql1);
                 pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(register_room.class.getName()).log(Level.SEVERE, null, ex);
            }
             String sq2="TRUNCATE TABLE customer";
            try {
                pst=conn.prepareStatement(sq2);
                 pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(register_room.class.getName()).log(Level.SEVERE, null, ex);
            } 
            String sq3="TRUNCATE TABLE one_alga";
            try {
                pst=conn.prepareStatement(sq3);
                 pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(register_room.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sq4="TRUNCATE TABLE cus_cond";
            try {
                pst=conn.prepareStatement(sq4);
                 pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(register_room.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sq5="TRUNCATE TABLE stu_alga";
            try {
                pst=conn.prepareStatement(sq5);
                 pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(register_room.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sq6="TRUNCATE TABLE three_alga";
            try {
                pst=conn.prepareStatement(sq6);
                 pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(register_room.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sq7="TRUNCATE TABLE two_alga";
            try {
                pst=conn.prepareStatement(sq7);
                 pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(register_room.class.getName()).log(Level.SEVERE, null, ex);
            }
           }
        }
        }
           cond_home ch=new cond_home();
           this.dispose();
           ch.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox last;
    // End of variables declaration//GEN-END:variables
}
